// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebPScanner.Data.Context;

#nullable disable

namespace WebPScanner.Data.Migrations
{
    [DbContext(typeof(WebPScannerDbContext))]
    [Migration("20260119141430_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("WebPScanner.Core.Entities.AggregateCategoryStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AggregateStatsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SavingsPercentSum")
                        .HasColumnType("REAL");

                    b.Property<long>("TotalSavingsBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AggregateStatsId");

                    b.HasIndex("Category")
                        .IsUnique();

                    b.ToTable("AggregateCategoryStats");
                });

            modelBuilder.Entity("WebPScanner.Core.Entities.AggregateImageTypeStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AggregateStatsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("PotentialSavingsBytes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SavingsPercentSum")
                        .HasColumnType("REAL");

                    b.Property<long>("TotalSizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AggregateStatsId");

                    b.HasIndex("MimeType")
                        .IsUnique();

                    b.ToTable("AggregateImageTypeStats");
                });

            modelBuilder.Entity("WebPScanner.Core.Entities.AggregateStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalEstimatedWebPSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalImagesFound")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalOriginalSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPagesCrawled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalSavingsPercentSum")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalScans")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AggregateStats");
                });

            modelBuilder.Entity("WebPScanner.Core.Entities.ConvertedImageZip", b =>
                {
                    b.Property<Guid>("DownloadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("TEXT");

                    b.HasKey("DownloadId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("ScanJobId");

                    b.ToTable("ConvertedImageZips");
                });

            modelBuilder.Entity("WebPScanner.Core.Entities.CrawlCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("NonWebPImagesFound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PagesDiscovered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PagesVisited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PendingUrlsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitedUrlsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScanJobId")
                        .IsUnique();

                    b.ToTable("CrawlCheckpoints");
                });

            modelBuilder.Entity("WebPScanner.Core.Entities.DiscoveredImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("EstimatedWebPSize")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("PageUrlsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PotentialSavingsPercent")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScanJobId");

                    b.ToTable("DiscoveredImages");
                });

            modelBuilder.Entity("WebPScanner.Core.Entities.ScanJob", b =>
                {
                    b.Property<Guid>("ScanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConvertToWebP")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("NonWebPImagesFound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PagesDiscovered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PagesScanned")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PriorityScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueuePosition")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubmissionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubmitterIp")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("ScanId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PriorityScore");

                    b.HasIndex("Status");

                    b.HasIndex("SubmitterIp");

                    b.ToTable("ScanJobs");
                });

            modelBuilder.Entity("WebPScanner.Core.Entities.AggregateCategoryStat", b =>
                {
                    b.HasOne("WebPScanner.Core.Entities.AggregateStats", "AggregateStats")
                        .WithMany("CategoryStats")
                        .HasForeignKey("AggregateStatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AggregateStats");
                });

            modelBuilder.Entity("WebPScanner.Core.Entities.AggregateImageTypeStat", b =>
                {
                    b.HasOne("WebPScanner.Core.Entities.AggregateStats", "AggregateStats")
                        .WithMany("ImageTypeStats")
                        .HasForeignKey("AggregateStatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AggregateStats");
                });

            modelBuilder.Entity("WebPScanner.Core.Entities.ConvertedImageZip", b =>
                {
                    b.HasOne("WebPScanner.Core.Entities.ScanJob", "ScanJob")
                        .WithMany()
                        .HasForeignKey("ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("WebPScanner.Core.Entities.CrawlCheckpoint", b =>
                {
                    b.HasOne("WebPScanner.Core.Entities.ScanJob", "ScanJob")
                        .WithMany()
                        .HasForeignKey("ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("WebPScanner.Core.Entities.DiscoveredImage", b =>
                {
                    b.HasOne("WebPScanner.Core.Entities.ScanJob", "ScanJob")
                        .WithMany("DiscoveredImages")
                        .HasForeignKey("ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("WebPScanner.Core.Entities.AggregateStats", b =>
                {
                    b.Navigation("CategoryStats");

                    b.Navigation("ImageTypeStats");
                });

            modelBuilder.Entity("WebPScanner.Core.Entities.ScanJob", b =>
                {
                    b.Navigation("DiscoveredImages");
                });
#pragma warning restore 612, 618
        }
    }
}
